#!/bin/bash

### ERROR check

#set -x
#function error_handler() {
# echo "ERROR" >&2
# exit 1
#


##need a seconds argument
#if [ -z $2 ]; then
#	cat ~/PyBox/manual.txt
#	exit 1
#fi


echo ' '
echo '### Welcome to PyBox ###'
echo ' '
#cd `dirname $1`

rt1="run"
rt2="interactive" # <- dont use this command
rt3="version"
#path=$(cd $(dirname $2); pwd)/$(basename $2) #we can know path 




if [ $1 == $rt1 ]; then # pip can use pip 

	if [ -f ~/PyBox/pyboxenv/bin/python ]; then

		if [ -f /bin/apt-get ]; then

			which sudo >/dev/null 2>&1

			if [ $? -eq 0 ]; then

				sudo ~/PyBox/pyboxenv/bin/python ${@:2} 	#read from second arguments
				echo ' '
				echo '### Done ###'
				echo ' '
			elif [ ! $? -eq 0 ]; then
				~/PyBox/pyboxenv/bin/python ${@:2}
				echo ' '
				echo '### Done ###'
				echo ' '
			fi
		elif [ -e /usr/local/Homebrew ]; then
				~/PyBox/pyboxenv/bin/python ${@:2}
				echo ' '
				echo '### Done ###'
				echo ' '
		fi
	else
		echo "pyboxenv is not found"
		echo ' '
		echo "You need run"
		echo " ' python ~/PyBox/setup.py install version-default ' or ' version-3 ' "
		echo " or "
		echo " ' python3 ~/PyBox/setup.py install version-default ' or ' version-3 '"
		exit 1
	fi


elif [ $1 == $rt2 ]; then

	if [ -f ~/PyBox/pyboxenv/bin/python ]; then

		if [ -f /bin/apt-get ]; then

			which sudo >/dev/null 2>&1
			if [ $? -eq 0 ]; then
				sudo ~/PyBox/pyboxenv/bin/python #$path
				echo ' '
				echo '### Done ###'
				echo ' '
				exit 1
			elif [ ! $? -eq 0 ]; then
				~/PyBox/pyboxenv/bin/python #$path
				echo ' '
				echo '### Done ###'
				echo ' '
				exit 1
			fi
			echo ' '
			echo '### Done ###'
			echo ' '

		elif [ -e /usr/local/Homebrew ]; then
				~/PyBox/pyboxenv/bin/python #$path
				echo ' '
				echo '### Done ###'
				echo ' '
				exit 1
				
		fi

	else
		echo "pyboxenv is not found"
		echo ' '
		echo "You need run ' python ~/PyBox/setup.py install version-default '"
		exit 1
	fi
else
	cat ~/PyBox/manual.txt
fi


### Next Update....###
#RESULT1=`ctl`
#RESULT2=`run`

#if [ $1 == $rt1 ]; then
#	echo ${RESULT1}

#elif [ $1 == $rt2 ]; then
#	echo ${RESULT2}
#fi