#!/bin/bash

### ERROR check

#set -x
#function error_handler() {
# echo "ERROR" >&2
# exit 1
#


##need a seconds argument
if [ -z $2 ]; then
	cat ~/Pydo/manual.txt
	exit 1
fi


echo ' '
echo '### Welcome to pydo ###'
echo ' '
#cd `dirname $1`

rt1="-p"
rt2="run"
path=$(cd $(dirname $2); pwd)/$(basename $2) #we can know path 




if [ $1 == $rt1 ]; then # pip can use pip 

	echo ' '
	echo 'Please wait.....'
	echo ' '

	which sudo >/dev/null 2>&1
	if [ $? -eq 0 ]; then
		sudo ~/Pydo/pydoenv/bin/python -m pip  ${@:2} 	#read from second arguments
		echo ' '
		echo '### Done ###'
		echo ' '
	elif [ ! $? -eq 0 ]; then
		~/Pydo/pydoenv/bin/python -m pip ${@:2}
		echo ' '
		echo '### Done ###'
		echo ' '
	fi



elif [ $1 == $rt2 ]; then

	which sudo >/dev/null 2>&1
	if [ $? -eq 0 ]; then
		sudo ~/Pydo/pydoenv/bin/python  $path
	elif [ ! $? -eq 0 ]; then
		~/Pydo/pydoenv/bin/python $path
		exit 1
	fi

else
	cat ~/Pydo/manual.txt
fi


### Next Update....###
#RESULT1=`ctl`
#RESULT2=`run`

#if [ $1 == $rt1 ]; then
#	echo ${RESULT1}

#elif [ $1 == $rt2 ]; then
#	echo ${RESULT2}
#fi
