#!/bin/bash

#set -x
#function error_handler() {
#  echo "ERROR" >&2
#  exit 1
#}

echo '### Uninstall ###'

#cd `dirname $0`

if [ -e $FILE ]; then
  echo "File exists."
fi

unset PATH=$HOME/Pydo/pydoenv/bin:$PATH
unset PATH=$HOME/Pydo:$PATH

which sudo >/dev/null 2>&1
if [ $? -eq 0 ]; then
	sudo rm -rf /usr/bin/pydo  #remove command
	sudo rm -rf ~/Pydo/pydoenv #remove venv
elif [ ! $? -eq 0 ]; then
	rm -rf /usr/bin/pydo
	rm -rf /Pydo/pydoenv
else
    echo '### complete ###'
fi

echo '### complete ###'
